# Required
NAME := Box2D
TYPE := static

SOURCE_DIR := $(PROJECT_ROOT)/src/Box2D
INCLUDES += -I$(PROJECT_ROOT)/src

# Deploy
EXPORT_AUTO_INCLUDES := 1
EXPORT_INCLUDE_FOLDER_NAME := Box2D
EXPORT_LIBNAME := Box2D
EXPORT_LIBVERSION := 2.2.1
