# Required
NAME := BoostHeaders
TYPE := header
HEADER_ONLY_LIB := 1

# Deploy
EXPORT_SYSTEM_LIB := 1
EXPORT_AUTO_INCLUDES := 1
EXPORT_INCLUDE_FOLDER_NAME := boost
EXPORT_LIBNAME := BoostHeaders
EXPORT_LIBVERSION := 1.55
